In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import numpy as np
import base64

In [2]:
df=pd.read_excel("../data/raw/Miriam VonAschen-Cook - UseOfForceProject-UoF Data w requested fields.xlsx")

In [13]:
df.loc[(df['Subject Gender'] == "Male"), "Subject Gender"] = "M"
df.loc[(df['Subject Gender'] == "Female"), "Subject Gender"] = "F"
df.loc[(df['Subject Gender'] == "Not Specified"), "Subject Gender"] = "N"
## Clean “Officer Serial Num” by converting it to integer
#df['Officer Serial Num'] = df['Officer Serial Num'].fillna(0).astype(np.int64)
df['Officer Serial Num'] = pd.to_numeric(df['Officer Serial Num'], errors='coerce').fillna(0).astype(np.int64)
## GO num to integer
df['GO Num'] = df['GO Num'].fillna(0).astype(np.int64)
## Removing leading/trailling spaces from strings
df = df.apply(lambda x: x.apply(str).str.strip().str.replace('#NAME\\?', '-') if x.dtype == 'object' else x)
df['Occurred Date'] = pd.to_datetime(df['Occurred Date'])

<ipython-input-13-01a5cefc687a>:10: FutureWarning: The default value of regex will change from True to False in a future version.
  df = df.apply(lambda x: x.apply(str).str.strip().str.replace('#NAME\\?', '-') if x.dtype == 'object' else x)

In [14]:
df.head(2)

,File Num,GO Num,CIT Certified Ind,Incident Type,Latitude,Longitude,Officer Gender,Officer Race,Officer Serial Num,Officer Title (as of Incident),Precinct,Sector,Subject Gender,Subject Race,Occurred Date
0,2015UOF-0336,20130000117995,N,Level 1 - Use of Force,NaN,NaN,M,White,5960,nan,X,nan,F,Asian,2015-03-03
1,2015UOF-0540,20130000117995,N,Level 1 - Use of Force,NaN,NaN,M,White,6413,nan,X,nan,F,Not Specified,2015-04-21

In [66]:
sel_dates = df[(df['Occurred Date'] >= '2017-01-01') & (df['Occurred Date'] <= '2018-06-30')]
sel_dates

,File Num,GO Num,CIT Certified Ind,Incident Type,Latitude,Longitude,Officer Gender,Officer Race,Officer Serial Num,Officer Title (as of Incident),Precinct,Sector,Subject Gender,Subject Race,Occurred Date
87,2017UOF-0504,20170000049196,N,Level 1 - Use of Force,NaN,NaN,M,White,6732,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-05-03
88,2017UOF-0178,20170000066157,N,Level 1 - Use of Force,NaN,NaN,M,Hispanic or Latino,6412,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-02-23
89,2017UOF-0177,20170000066157,N,Level 1 - Use of Force,NaN,NaN,M,Hispanic or Latino,7580,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-02-23
90,2017UOF-0176,20170000066157,N,Level 1 - Use of Force,NaN,NaN,M,White,7496,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-02-23
91,2017UOF-0348,20170000116098,N,Level 1 - Use of Force,NaN,NaN,M,White,6413,POLICE OFFICER,X,nan,M,Black or African American,2017-04-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12753,2017UOF-1380,20170000410990,Y,Level 1 - Use of Force,47.73286,-122.33836,M,White,8371,POLICE OFFICER,North,NORA,F,Black or African American,2017-11-05
12761,2017UOF-0865,20170000275819,Y,Level 1 - Use of Force,47.73356,-122.35664,M,White,7794,POLICE OFFICER,North,NORA,M,Not Specified,2017-07-28
12763,2017UOF-0017,20170000008372,Y,Level 1 - Use of Force,47.73414,-122.33592,M,White,6296,POLICE OFFICER,North,NORA,M,White,2017-01-07
12766,2017UOF-1374,20170000395984,Y,Level 1 - Use of Force,-1.00000,-1.00000,M,White,7682,POLICE OFFICER,-,nan,M,Not Specified,2017-10-25
12767,2017UOF-1582,20170000452034,Y,Level 1 - Use of Force,-1.00000,-1.00000,M,White,6942,POLICE OFFICER,-,nan,M,Black or African American,2017-12-08

In [67]:
total_all = sel_dates.groupby(['File Num', 'GO Num', 'CIT Certified Ind', 'Incident Type', 'Sector', 'Precinct']).size()
total_all

File Num      GO Num          CIT Certified Ind  Incident Type           Sector  Precinct
2017UOF-0001  20170000004454  Y                  Level 1 - Use of Force  EDWARD  East        1
2017UOF-0002  20170000000695  Y                  Level 1 - Use of Force  ROBERT  South       1
2017UOF-0003  20170000003534  Y                  Level 1 - Use of Force  BOY     North       1
2017UOF-0004  20170000003534  N                  Level 1 - Use of Force  BOY     North       1
2017UOF-0005  20170000002086  N                  Level 1 - Use of Force  KING    West        1
                                                                                            ..
2018UOF-1351  20180000215597  N                  Level 1 - Use of Force  NORA    North       1
2018UOF-1352  20180000215597  N                  Level 1 - Use of Force  NORA    North       1
2018UOF-1353  20180000215597  Y                  Level 1 - Use of Force  NORA    North       1
2018UOF-1354  20180000215597  Y                  Level 1 - Use of Force  NORA    North       1
2018UOF-1411  20180000228327  Y                  Level 1 - Use of Force  NORA    North       1
Length: 2635, dtype: int64

# SEL_DATES FOR -YES CIT

In [61]:
yes_cit = sel_dates[sel_dates['CIT Certified Ind']=='Y']
yes_cit

,File Num,GO Num,CIT Certified Ind,Incident Type,Latitude,Longitude,Officer Gender,Officer Race,Officer Serial Num,Officer Title (as of Incident),Precinct,Sector,Subject Gender,Subject Race,Occurred Date
7529,2017UOF-0113,20160000405996,Y,Level 1 - Use of Force,NaN,NaN,M,White,6666,POLICE OFFICER,X,nan,M,Black or African American,2017-02-08
7530,2017UOF-0115,20160000405996,Y,Level 1 - Use of Force,NaN,NaN,M,White,6298,POLICE OFFICER,X,nan,M,Not Specified,2017-02-08
7531,2017UOF-0114,20160000405996,Y,Level 1 - Use of Force,NaN,NaN,M,White,6776,POLICE OFFICER,X,nan,M,Not Specified,2017-02-08
7538,2017UOF-0156,20170000004561,Y,Level 1 - Use of Force,NaN,NaN,M,Not Specified,6864,POLICE OFFICER,X,nan,N,Not Specified,2017-02-08
7539,2017UOF-0154,20170000004561,Y,Level 2 - Use of Force,NaN,NaN,M,White,6146,POLICE SERGEANT,X,nan,N,Not Specified,2017-02-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12753,2017UOF-1380,20170000410990,Y,Level 1 - Use of Force,47.73286,-122.33836,M,White,8371,POLICE OFFICER,North,NORA,F,Black or African American,2017-11-05
12761,2017UOF-0865,20170000275819,Y,Level 1 - Use of Force,47.73356,-122.35664,M,White,7794,POLICE OFFICER,North,NORA,M,Not Specified,2017-07-28
12763,2017UOF-0017,20170000008372,Y,Level 1 - Use of Force,47.73414,-122.33592,M,White,6296,POLICE OFFICER,North,NORA,M,White,2017-01-07
12766,2017UOF-1374,20170000395984,Y,Level 1 - Use of Force,-1.00000,-1.00000,M,White,7682,POLICE OFFICER,-,nan,M,Not Specified,2017-10-25
12767,2017UOF-1582,20170000452034,Y,Level 1 - Use of Force,-1.00000,-1.00000,M,White,6942,POLICE OFFICER,-,nan,M,Black or African American,2017-12-08

In [75]:
# yes_cit.groupby('GO Num').size()
cit_yes = sel_dates[sel_dates['CIT Certified Ind']=='Y']
total_yes = cit_yes.groupby(['File Num', 'GO Num', 'CIT Certified Ind', 'Incident Type', 'Sector', 'Precinct']).size()
perc_yescit = len(total_yes)/len(total_all)*100
perc_yescit

52.82732447817837

In [84]:
# len(sel_dates[sel_dates['CIT Certified Ind']=='Y'])/len(sel_dates)
# #53

# SEL_DATES FOR CIT-NO

In [76]:
cit_no = sel_dates[sel_dates['CIT Certified Ind']=='N']#.count()
cit_no

,File Num,GO Num,CIT Certified Ind,Incident Type,Latitude,Longitude,Officer Gender,Officer Race,Officer Serial Num,Officer Title (as of Incident),Precinct,Sector,Subject Gender,Subject Race,Occurred Date
87,2017UOF-0504,20170000049196,N,Level 1 - Use of Force,NaN,NaN,M,White,6732,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-05-03
88,2017UOF-0178,20170000066157,N,Level 1 - Use of Force,NaN,NaN,M,Hispanic or Latino,6412,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-02-23
89,2017UOF-0177,20170000066157,N,Level 1 - Use of Force,NaN,NaN,M,Hispanic or Latino,7580,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-02-23
90,2017UOF-0176,20170000066157,N,Level 1 - Use of Force,NaN,NaN,M,White,7496,POLICE OFFICER,X,nan,M,Hispanic or Latino,2017-02-23
91,2017UOF-0348,20170000116098,N,Level 1 - Use of Force,NaN,NaN,M,White,6413,POLICE OFFICER,X,nan,M,Black or African American,2017-04-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7487,2017UOF-0347,20170000108900,N,Level 1 - Use of Force,47.76213,-122.34807,M,White,7496,POLICE OFFICER,X,nan,M,Not Specified,2017-04-03
7491,2017UOF-1331,20170000406529,N,Level 1 - Use of Force,-1.00000,-1.00000,M,White,8456,POLICE OFFICER PROBATION,-,nan,M,White,2017-11-02
7492,2017UOF-1378,20170000409541,N,Level 1 - Use of Force,-1.00000,-1.00000,M,White,7760,POLICE OFFICER,-,nan,F,Not Specified,2017-11-14
7493,2017UOF-1573,20170000438592,N,Level 1 - Use of Force,-1.00000,-1.00000,F,White,8444,POLICE OFFICER,-,nan,F,Black or African American,2017-11-28
7494,2018UOF-1009,20180000057344,N,Level 1 - Use of Force,-1.00000,-1.00000,F,White,8566,POLICE STUDENT OFFICER,-,nan,M,Black or African American,2018-02-15

# PERCENTAGE OF THE SELECT NO CIT  DATES

In [82]:
cit_no = sel_dates[sel_dates['CIT Certified Ind']=='N']
total_no = cit_no.groupby(['File Num', 'GO Num', 'CIT Certified Ind', 'Incident Type', 'Sector', 'Precinct']).size()
perc_nocit = len(total_no)/len(total_all)*100
perc_nocit

47.17267552182163

In [78]:
# len(sel_dates[sel_dates['CIT Certified Ind']=='N'])/len(sel_dates)*100
# #47

# Call DATA

In [86]:
df_calls = pd.read_csv("../data/processed/MVAallcases_cleaned.csv")

In [88]:
df_calls.head()

,Officer Dispatch UID,Dispatch ID,CAD Event ID,Officer Serial Num,AS Of Officer Title,As_On_Officer Precinct_ID,As_On_Officer Precinct_Desc,As_On_Officer Squad_Desc,Partner Officer Serial Num,Clear By Desc,...,First Dispatch Time,Clear Time,Total Service Time,Precinct,Sector,Beat,Dispatch Address,Blurred_Latitude,Blurred_Longitude,Year
0,20150003320461M37670,20150003320461M3,-2147483648,7670,POLICE OFFICER,B110,WEST PCT,WEST PCT 1ST W - DAVID/MARY,-,UNABLE TO LOCATE INCIDENT OR COMPLAINANT,...,2015-09-22 12:41:17.00,2015-09-22 12:54:59.00,13.0,WEST,MARY,M3,SENECA ST / 5 AV,47.607979,-122.333107,2015
1,20150002457253E936908,20150002457253E93,-2147483648,6908,POLICE OFFICER,B250,SOUTHWEST PCT,SOUTHWEST PCT - 3RD WATCH - F/W RELIEF,6908,ASSISTANCE RENDERED,...,2015-07-18 00:45:08.00,2015-07-18 00:48:57.00,3.0,EAST,EDWARD,E2,11 AV / E PIKE ST,47.614092,-122.318142,2015
2,20150004481092K337766,20150004481092K33,-2147483648,7766,POLICE OFFICER,B110,WEST PCT,WEST PCT 2ND W - K/Q RELIEF,-,REPORT WRITTEN (NO ARREST),...,2015-12-28 17:02:28.00,2015-12-28 19:18:20.00,23.0,WEST,DAVID,D2,810 VIRGINIA ST,47.616053,-122.336166,2015
3,20150001910072R335465,20150001910072R33,-2147483648,5465,POLICE OFFICER,B230,SOUTH PCT,SOUTH PCT 2ND W - ROBERT,5465,REPORT WRITTEN (NO ARREST),...,2015-06-08 12:12:05.00,2015-06-08 15:29:30.00,23.0,SOUTH,ROBERT,R2,3220 HUNTER BV S,47.574504,-122.284878,2015
4,20150004225892R116880,20150004225892R11,-2147483648,6880,POLICE OFFICER,B230,SOUTH PCT,SOUTH PCT 2ND W - ROBERT,-,REPORT WRITTEN (NO ARREST),...,2015-12-05 14:57:54.00,2015-12-05 17:39:51.00,3.0,SOUTH,ROBERT,R2,2909 S HILL ST,47.584479,-122.294590,2015

In [89]:
sel_dat = df_calls[(df_calls['First Dispatch Time'] >= '2017-01-01') & (df_calls['First Dispatch Time'] <= '2018-06-30')]

In [90]:
sel_dat

,Officer Dispatch UID,Dispatch ID,CAD Event ID,Officer Serial Num,AS Of Officer Title,As_On_Officer Precinct_ID,As_On_Officer Precinct_Desc,As_On_Officer Squad_Desc,Partner Officer Serial Num,Clear By Desc,...,First Dispatch Time,Clear Time,Total Service Time,Precinct,Sector,Beat,Dispatch Address,Blurred_Latitude,Blurred_Longitude,Year
1868136,20170002056842M926885,20170002056842M92,-2147483648,6885,POLICE OFFICER,B110,WEST PCT,WEST PCT 2ND W - MARY BEATS,5560,ASSISTANCE RENDERED,...,2017-06-08 14:57:43.00,2017-06-08 15:36:41.00,38.0,WEST,MARY,M3,4 AV / PINE ST,47.611207,-122.337596,2017
1868137,20170002843371D18388,20170002843371D1,-2147483648,8388,POLICE OFFICER,B110,WEST PCT,WEST PCT 1ST W - DAVID/MARY,-,REPORT WRITTEN (NO ARREST),...,2017-08-03 04:50:54.00,2017-08-03 06:02:34.00,3.0,WEST,DAVID,D1,2124 3 AV,47.613551,-122.342843,2017
1868138,20170004221282L028408,20170004221282L02,-2147483648,8408,POLICE OFFICER,B120,NORTH PCT,NORTH PCT 2ND W - LINCOLN,8435,ASSISTANCE RENDERED,...,2017-11-14 11:24:13.00,2017-11-14 12:13:07.00,34.0,NORTH,LINCOLN,L3,LAKE CITY WY NE / NE 125 ST,47.719278,-122.295234,2017
1868139,20170001614582R37677,20170001614582R3,-2147483648,7677,POLICE OFFICER,B230,SOUTH PCT,SOUTH PCT 2ND W - ROBERT,-,FALSE COMPLAINT/UNFOUNDED,...,2017-05-08 15:43:47.00,2017-05-08 16:25:09.00,2.0,SOUTH,OCEAN,O3,5701 1 AV S,47.551504,-122.334217,2017
1868140,20170001110972C317748,20170001110972C31,-2147483648,7748,POLICE OFFICER,B240,EAST PCT,EAST PCT 2ND W - CHARLIE,-,REPORT WRITTEN (NO ARREST),...,2017-03-30 12:28:40.00,2017-03-30 13:53:44.00,18.0,EAST,CHARLIE,C2,1700 17 AV 414,47.617027,-122.310145,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4348739,20180000411983D117622,20180000411983D11,-2147483648,7622,POLICE OFFICER,B110,WEST PCT,WEST PCT 3RD W - DAVID,7638,ASSISTANCE RENDERED,...,2018-02-03 01:30:57.00,2018-02-03 01:36:01.00,4.0,WEST,DAVID,D1,2928 1 AV [DOMINOS,47.617309,-122.353169,2018
4348741,20180000863561M37634,20180000863561M3,-2147483648,7634,POLICE OFFICER,B110,WEST PCT,WEST PCT 1ST W - DAVID/MARY,-,RESPONDING UNIT(S) CANCELLED BY RADIO,...,2018-03-10 07:18:48.00,2018-03-10 07:22:54.00,4.0,WEST,MARY,M1,102 PIKE ST[STARBUCKS,47.609053,-122.339459,2018
4348742,2018000075272V77707770,2018000075272V7770,-2147483648,7770,POLICE OFFICER,B240,EAST PCT,EAST PCT 3RD W - CHARLIE,-,ASSISTANCE RENDERED,...,2018-03-01 21:01:18.00,2018-03-02 03:03:49.00,2.0,WEST,KING,K2,ALASKAN WY S / S JACKSON ST,47.599206,-122.335911,2018
4348745,20180001601883W738407,20180001601883W73,-2147483648,8407,POLICE OFFICER,B250,SOUTHWEST PCT,SOUTHWEST PCT 2ND W - WILLIAM,8399,OTHER REPORT MADE,...,2018-05-05 21:22:46.00,2018-05-05 21:37:26.00,10.0,SOUTHWEST,WILLIAM,W1,1228 HARBOR AV SW,47.591314,-122.382375,2018
4348748,20180000332032K927569,20180000332032K92,-2147483648,7569,POLICE OFFICER,B110,WEST PCT,WEST PCT 2ND W - KING BEATS,7569,ASSISTANCE RENDERED,...,2018-01-27 17:25:08.00,2018-01-27 18:11:29.00,46.0,WEST,KING,K2,1 AV S / S KING ST,47.598291,-122.334194,2018

In [102]:
sel_dat.groupby('Dispatch ID')['Dispatch ID'].count().sort_values(ascending=False).head(10)

Dispatch ID
2017000195300490     16
20170004107472W82    16
2017000219301Z3      16
2017000369370885     16
20180000436782J81    16
2018000090214297     16
20180000841652M92    16
20180000492542J81    16
2017000268908Z4      16
2017000157707Z20     16
Name: Dispatch ID, dtype: int64

In [98]:
sel_dat.groupby('Officer Dispatch UID')['Officer Dispatch UID'].count().sort_values(ascending=False).head(10)

Officer Dispatch UID
20170004790313K18436     4
20170004799493D17638     4
20170004800743F738379    4
20170004800743F738509    4
20170004790113D37627     4
20170004790113D36834     4
20170004800183Q238537    4
20170004800193M27325     4
20170004796042E27288     4
20170004793022C537782    4
Name: Officer Dispatch UID, dtype: int64

In [115]:
# test_calls = sel_dat.groupby(['Dispatch ID', 'CAD Event ID']).size()
# test_calls
test_calls = sel_dat.groupby(['Dispatch ID']).size()#.sort_values(by='Dispatch ID').head(5)
test_calls.head()

Dispatch ID
20160004689333B      1
20160004689521K01    1
20160004689521K1     1
20160004689943Q2     4
20160004689943Q3     1
dtype: int64

In [ ]:
tot_calls = sel_dat.groupby(['Officer Dispatch UID', 'Dispatch ID', 'CAD Event ID']).size()